research_task:
  description: >
    Realize uma pesquisa na Wikipedia sobre o seguinte tópico: "{topic}".

    Instruções:
    - Busque informações relevantes, atualizadas e de qualidade.
    - Sintetize o conteúdo em pelo menos três parágrafos informativos.
    - O texto deve ser claro, objetivo e livre de opiniões.
    - Não inclua conteúdo especulativo ou desnecessário.
    - Mantenha a linguagem técnica acessível e precisa.
  
  expected_output: >
    Um resumo em formato de texto corrido com pelo menos cinco parágrafos informativos,
    contendo dados relevantes e confiáveis sobre o tópico pesquisado, extraídos da Wikipedia.

  agent: researcher

reporting_task:
  description: >
    Com base no conteúdo fornecido pelo pesquisador, escreva um artigo informativo com as seguintes características:

    - Mínimo de 300 palavras.
    - Estrutura clara com título, introdução, desenvolvimento e conclusão.
    - Texto em português formal, natural e coeso.
    - Não mencione que o conteúdo é gerado por IA ou baseado na Wikipedia.
    - Enfatize a importância do tema quando possível.

  expected_output: >
    Um artigo completo, fluente, com linguagem humana, estruturado em parágrafos e com no mínimo 300 palavras.

  agent: reporting_analyst
  depends_on: [research_task]

review_task:
  description: >
    Revise o artigo gerado, atentando-se aos seguintes pontos:

    - Ortografia, gramática e pontuação.
    - Clareza, coesão e fluidez textual.
    - Consistência do conteúdo com o objetivo proposto.
    - Estrutura lógica com começo, meio e fim.
    - Sugestões de melhoria, caso necessário, com foco em legibilidade e precisão técnica.
    - Se necessário, reescreva partes para maior coerência e completude argumentativa.

    Organize o conteúdo revisado no **formato de artigo textual estruturado**, obedecendo os seguintes elementos obrigatórios:

    - Título centralizado (representativo e impactante)
    - Nome(s) do(s) autor(es) alinhados à direita (Deixe o nome vazio)
    - Seções com subtítulos à esquerda (Resumo, Introdução, Desenvolvimento, etc.)
    - Conclusão clara e bem fundamentada
    - Referências ao final, no padrão ABNT, com link e data de acesso
    - Texto justificado, com recuo de parágrafo (1 TAB ou 1,25 cm)

    Aplique as normas de formatação abaixo:

    - Papel: A4 (branco ou reciclado)
    - Margens: esquerda e superior de 3 cm; direita e inferior de 2 cm
    - Fonte: Times New Roman, Arial, Calibri ou Verdana, tamanho 12
    - Espaçamento entre linhas: 1,5 no corpo do texto; simples em citações longas, notas de rodapé e referências
    - Tamanho da fonte 10 para: citações longas (com mais de 3 linhas), rodapés, paginação, referências e legendas
    - Paginação: canto superior direito, em algarismos arábicos, fonte 10 (primeira página é contada, mas não numerada)
    - Distância entre seções: uma linha em branco (espaço 1,5)
    - Texto final deve ser justificado

  expected_output: >
    Um artigo **revisado e polido, pronto para publicação ou submissão institucional**, contendo:

    - Título centralizado
    - Nome(s) do(s) autor(es) à direita
    - Seções numeradas e divididas por subtítulos com espaçamento e recuo apropriado
    - Conclusão clara, com reforço dos pontos principais e possíveis implicações
    - Referências bibliográficas no padrão ABNT, com título da fonte, link e data de acesso
    - Todo o conteúdo respeitando a formatação especificada: margens, fonte, espaçamento, alinhamento, recuo de parágrafo, etc.

    O artigo deve ter uma leitura fluida, com linguagem técnica acessível, estrutura lógica e conteúdo coerente com o objetivo original.

  agent: reviewer
  depends_on: [reporting_task]
