research_task:
  description: >
    Realize uma pesquisa sobre o tópico fornecido utilizando a Wikipedia.

    Instruções:
    - Busque informações relevantes, atualizadas e de qualidade.
    - Sintetize o conteúdo em pelo menos três parágrafos informativos.
    - O texto deve ser claro, objetivo e livre de opiniões.
    - Não inclua conteúdo especulativo ou desnecessário.
    - Mantenha a linguagem técnica acessível e precisa.

  expected_output: >
    Um resumo coeso de pelo menos três parágrafos sobre o tema, contendo os pontos principais da pesquisa.

  agent: researcher

reporting_task:
  description: >
    Com base no conteúdo fornecido pelo pesquisador, escreva um artigo informativo com as seguintes características:

    - Mínimo de 300 palavras.
    - Estrutura clara com título, introdução, desenvolvimento e conclusão.
    - Texto em português formal, natural e coeso.
    - Não mencione que o conteúdo é gerado por IA ou baseado na Wikipedia.
    - Enfatize a importância do tema quando possível.

  expected_output: >
    Um artigo completo, fluente, com linguagem humana, estruturado em parágrafos e com no mínimo 300 palavras.

  agent: reporting_analyst
  depends_on: [research_task]

review_task:
  description: >
    Revise o artigo gerado, atentando-se aos seguintes pontos:

    - Ortografia, gramática e pontuação.
    - Clareza e fluidez textual.
    - Consistência do conteúdo com o objetivo proposto.
    - Sugestões de melhoria, se necessário.

    Se tudo estiver correto, apenas reescreva o texto corrigido com pequenas melhorias estilísticas.

  expected_output: >
    Uma versão revisada e polida do artigo, pronta para publicação.

    O conteúdo final **deve estar formatado em JSON**, seguindo esta estrutura:

    {
      "titulo": "Título do artigo",
      "secoes": [
        {"subtitulo": "Introdução", "conteudo": "Texto da introdução"},
        {"subtitulo": "Desenvolvimento", "conteudo": "Texto do desenvolvimento"}
      ],
      "conclusao": "Texto da conclusão",
      "referencias": [
        {"titulo": "Fonte 1", "link": "https://..."},
        {"titulo": "Fonte 2", "link": "https://..."}
      ]
    }

  agent: reviewer
  depends_on: [reporting_task]
